### ISSUE TITLE
代码中的一个小bug

### ISSUE THREAD

**Issue by cmh14** [xiaobaicxy/text-classification-BiLSTM-Attention-pytorch#1]
作者您好，我学习了您的这篇代码双向LSTM结合Attention的代码，对于加深我对于这些模型的理解有很大帮助，这里先对作者您的工作表示感谢，
不过在实际运行中这个demo的代码存在一些小小的问题，在LSTM类中初始化h_0和c_0时候需要在后面加上to(device),否则在使用GPU加速训练时候产生了input变量在cuda而hidden变量在CPU的错误

**Comment by xiaobaicxy** [comment]
> 作者您好，我学习了您的这篇代码双向LSTM结合Attention的代码，对于加深我对于这些模型的理解有很大帮助，这里先对作者您的工作表示感谢，
> 不过在实际运行中这个demo的代码存在一些小小的问题，在LSTM类中初始化h_0和c_0时候需要在后面加上to(device),否则在使用GPU加速训练时候产生了input变量在cuda而hidden变量在CPU的错误

您好，谢谢您的提醒。我这个版本只在cpu上测过。后来我用在gpu上测也有这个问题，我忘记更新了。特别感谢您的提醒，我尽快会将新版本代码发布出来。
